[project]
name = "inferringbehavioralstatefromkinematics"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "ssm@git+https://github.com/lindermanlab/ssm.git",
  "lds@git+https://github.com/joacorapela/lds.git"
]
